/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.lab;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppIntTest {
    @Test void messageHash() {
        assertNotNull(new Message("hello").getTextHash(), "message should have a hash");
    }
}
